#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import logging
import math
import re
import subprocess
import sys
import traceback
from pathlib import Path


ROOT = Path(__file__).resolve().parent
DEFAULT_SCRIPTS = [
    "collapse_and_fit_fanh.py",
    "measure_gamma_and_refit.py",
    "fit_vw_amplitude.py",
]


def parse_bool(value):
    if isinstance(value, bool):
        return value
    text = str(value).strip().lower()
    if text in {"1", "true", "t", "yes", "y", "on"}:
        return True
    if text in {"0", "false", "f", "no", "n", "off"}:
        return False
    raise argparse.ArgumentTypeError(f"Could not interpret boolean value: {value}")


def parse_args():
    p = argparse.ArgumentParser(
        description="Create _tosc copies of the main fit scripts, rerun them, and compare amplitude prefactors."
    )
    p.add_argument("--t-osc", type=float, default=1.5)
    p.add_argument("--scripts", nargs="*", default=DEFAULT_SCRIPTS)
    p.add_argument("--refit", type=parse_bool, default=True)
    p.add_argument("--lattice-only", type=parse_bool, default=False)
    p.add_argument("--outdir-base", type=str, default="results_tosc")
    return p.parse_args()


def to_native(obj):
    if isinstance(obj, dict):
        return {str(k): to_native(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [to_native(v) for v in obj]
    if isinstance(obj, Path):
        return str(obj)
    return obj


def save_json(path: Path, payload):
    path.write_text(json.dumps(to_native(payload), indent=2, sort_keys=True))


def configure_logging(results_dir: Path):
    results_dir.mkdir(parents=True, exist_ok=True)
    log_path = results_dir / "apply_tosc_and_refit.log"
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
        handlers=[
            logging.FileHandler(log_path, mode="w"),
            logging.StreamHandler(sys.stdout),
        ],
    )
    return log_path


def error_exit(results_dir: Path, message: str):
    payload = {"status": "error", "message": message, "traceback": traceback.format_exc()}
    save_json(results_dir / "_error.json", payload)
    print(json.dumps({"status": "error", "message": message}, sort_keys=True))
    return 1


def insert_tosc_constant(text: str, t_osc: float) -> str:
    anchor = "ROOT = Path(__file__).resolve().parent\n"
    constant = f"T_OSC = {t_osc!r}\n"
    if "T_OSC =" in text:
        text = re.sub(r"^T_OSC\s*=.*$", constant.strip(), text, count=1, flags=re.MULTILINE)
        return text
    if anchor in text:
        return text.replace(anchor, anchor + constant, 1)
    return constant + text


def replace_power_normalization(text: str) -> str:
    pattern = re.compile(r"np\.power\((.+?),\s*1\.5\)")

    def repl(match):
        expr = match.group(1).strip()
        if "T_OSC" in expr:
            return match.group(0)
        if ("tp" in expr) or ("x" in expr):
            return f"np.power(({expr}) / T_OSC, 1.5)"
        return match.group(0)

    return pattern.sub(repl, text)


def apply_lattice_only_patch(text: str, stem: str) -> str:
    if stem in {"collapse_and_fit_fanh", "measure_gamma_and_refit"}:
        text = re.sub(
            r"ODE_CANDIDATES\s*=\s*\[[^\]]*\]",
            "ODE_CANDIDATES = []",
            text,
            count=1,
            flags=re.DOTALL,
        )
    return text


def make_tosc_copy(src: Path, dst: Path, t_osc: float, lattice_only: bool = False):
    text = src.read_text()
    text = insert_tosc_constant(text, t_osc)
    text = replace_power_normalization(text)
    if lattice_only:
        text = apply_lattice_only_patch(text, src.stem)
    header = (
        "#!/usr/bin/env python3\n"
        f"# Auto-generated by apply_tosc_and_refit.py from {src.name}\n"
        f"# Uses T_OSC = {t_osc!r} and replaces tp**(3/2) or x**(3/2) factors with (./T_OSC)**(3/2)\n"
    )
    if lattice_only:
        header += "# Lattice-only mode: optional ODE loading disabled in the generated copy\n"
    if text.startswith("#!/usr/bin/env python3\n"):
        body = text.split("\n", 1)[1]
        text = header + body
    else:
        text = header + text
    dst.write_text(text)
    dst.chmod(0o755)


def default_old_outputs(script_name: str, lattice_only: bool):
    stem = Path(script_name).stem
    if stem == "collapse_and_fit_fanh":
        if lattice_only:
            return [ROOT / "results_collapse_v9_H15H20" / "global_fit.json"]
        return [ROOT / "results_collapse" / "global_fit.json"]
    if stem == "measure_gamma_and_refit":
        if lattice_only:
            return [ROOT / "results_gamma_v9_H15H20_scalar" / "global_twoexp_fit.json"]
        return [ROOT / "results_gamma" / "global_twoexp_fit.json"]
    if stem == "fit_vw_amplitude":
        return [
            ROOT / "results_vw_amp" / "global_fit_optionA.json",
            ROOT / "results_vw_amp" / "global_fit_optionB.json",
        ]
    return []


def default_new_outputs(script_name: str, results_root: Path):
    stem = Path(script_name).stem
    run_dir = results_root / stem
    if stem == "collapse_and_fit_fanh":
        return run_dir, [run_dir / "global_fit.json"]
    if stem == "measure_gamma_and_refit":
        return run_dir, [run_dir / "global_twoexp_fit.json"]
    if stem == "fit_vw_amplitude":
        return run_dir, [run_dir / "global_fit_optionA.json", run_dir / "global_fit_optionB.json"]
    return run_dir, []


def build_command(script_copy: Path, script_name: str, results_root: Path, lattice_only: bool):
    stem = Path(script_name).stem
    run_dir, _ = default_new_outputs(script_name, results_root)
    cmd = [sys.executable, str(script_copy)]
    if stem == "collapse_and_fit_fanh":
        cmd += ["--outdir", str(run_dir)]
        if lattice_only:
            cmd += ["--fixed-vw", "0.9", "--h-values", "1.5", "2.0"]
    elif stem == "measure_gamma_and_refit":
        collapse_dir = results_root / "collapse_and_fit_fanh"
        best_beta = collapse_dir / "best_beta.json"
        collapse_fit = collapse_dir / "global_fit.json"
        finf_tail = collapse_dir / "Finf_tail.csv"
        if not best_beta.exists():
            best_beta = ROOT / ("results_collapse_v9_H15H20" if lattice_only else "results_collapse") / "best_beta.json"
        if not collapse_fit.exists():
            collapse_fit = ROOT / ("results_collapse_v9_H15H20" if lattice_only else "results_collapse") / "global_fit.json"
        if not finf_tail.exists():
            finf_tail = ROOT / ("results_collapse_v9_H15H20" if lattice_only else "results_collapse") / "Finf_tail.csv"
        cmd += [
            "--outdir",
            str(run_dir),
            "--best-beta",
            str(best_beta),
            "--collapse-fit",
            str(collapse_fit),
            "--finf-tail",
            str(finf_tail),
        ]
        if lattice_only:
            cmd += ["--skip-ode", "--scalar-only", "--h-values", "1.5", "2.0"]
    elif stem == "fit_vw_amplitude":
        cmd += ["--outdir", str(run_dir), "--vw-folders", "v3", "v5", "v7", "v9", "--fix-tc"]
        if lattice_only:
            cmd += ["--h-values", "1.5", "2.0"]
    else:
        cmd += ["--outdir", str(run_dir)]
    return cmd


def run_script(cmd, log_path: Path):
    proc = subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True)
    log_path.write_text(
        f"$ {' '.join(cmd)}\n\n[stdout]\n{proc.stdout}\n\n[stderr]\n{proc.stderr}\n"
    )
    return proc.returncode, proc.stdout, proc.stderr


def is_number(value):
    return isinstance(value, (int, float)) and math.isfinite(float(value))


def extract_amplitudes_from_payload(payload, prefix=""):
    rows = {}
    if isinstance(payload, dict):
        for key, value in payload.items():
            if key in {"A0", "A1", "A_inf", "Ainf", "A"} and is_number(value):
                rows[prefix + key] = float(value)
            elif key == "F_inf" and isinstance(value, dict):
                for subkey, subval in value.items():
                    if isinstance(subval, dict) and "value" in subval and is_number(subval["value"]):
                        rows[f"{prefix}F_inf[{subkey}]"] = float(subval["value"])
                    elif is_number(subval):
                        rows[f"{prefix}F_inf[{subkey}]"] = float(subval)
            elif isinstance(value, dict):
                rows.update(extract_amplitudes_from_payload(value, prefix + key + "."))
    return rows


def load_json(path: Path):
    return json.loads(path.read_text())


def compare_amplitudes(old_jsons, new_jsons, t_osc: float, script_name: str):
    scale = float(t_osc ** 1.5)
    rows = []
    old_map = {}
    new_map = {}
    for path in old_jsons:
        if path.exists():
            prefix = path.stem + "."
            old_map.update(extract_amplitudes_from_payload(load_json(path), prefix=prefix))
    for path in new_jsons:
        if path.exists():
            prefix = path.stem + "."
            new_map.update(extract_amplitudes_from_payload(load_json(path), prefix=prefix))

    for key in sorted(set(old_map) & set(new_map)):
        old_val = old_map[key]
        new_val = new_map[key]
        predicted = old_val * scale
        ratio = new_val / predicted if abs(predicted) > 1.0e-18 else math.nan
        rows.append(
            {
                "script": script_name,
                "amplitude_key": key,
                "old_value": old_val,
                "new_value": new_val,
                "predicted_new_from_old": predicted,
                "ratio": ratio,
            }
        )
    return rows


def main():
    args = parse_args()
    results_root = ROOT / args.outdir_base
    log_path = configure_logging(results_root)
    try:
        scale_factor = float(args.t_osc ** 1.5)
        summary = {
            "status": "ok",
            "t_osc": float(args.t_osc),
            "scale_factor_tosc_3half": scale_factor,
            "refit": bool(args.refit),
            "lattice_only": bool(args.lattice_only),
            "scripts": {},
        }
        comparison_rows = []

        for script_name in args.scripts:
            src = (ROOT / script_name).resolve()
            if not src.exists():
                logging.warning("Missing script %s; skipping", script_name)
                summary["scripts"][script_name] = {"status": "missing"}
                continue

            dst = src.with_name(src.stem + "_tosc.py")
            make_tosc_copy(src, dst, args.t_osc, lattice_only=bool(args.lattice_only))
            logging.info("Wrote %s", dst.relative_to(ROOT))

            run_dir, new_jsons = default_new_outputs(script_name, results_root)
            old_jsons = default_old_outputs(script_name, lattice_only=bool(args.lattice_only))
            script_entry = {
                "status": "prepared",
                "copy": str(dst),
                "run_dir": str(run_dir),
                "old_jsons": [str(p) for p in old_jsons],
                "new_jsons": [str(p) for p in new_jsons],
            }

            if args.refit:
                cmd = build_command(dst, script_name, results_root, lattice_only=bool(args.lattice_only))
                log_file = results_root / f"{Path(script_name).stem}.log"
                logging.info("Running %s", " ".join(cmd))
                code, stdout, stderr = run_script(cmd, log_file)
                script_entry.update(
                    {
                        "status": "ok" if code == 0 else "failed",
                        "returncode": int(code),
                        "command": cmd,
                        "log_file": str(log_file),
                    }
                )
                if code != 0:
                    logging.warning("Run failed for %s; see %s", script_name, log_file)
                    summary["scripts"][script_name] = script_entry
                    continue

            rows = compare_amplitudes(old_jsons, new_jsons, args.t_osc, script_name)
            script_entry["n_amplitude_rows"] = len(rows)
            comparison_rows.extend(rows)
            summary["scripts"][script_name] = script_entry

        csv_path = results_root / "amp_conversion_check.csv"
        with csv_path.open("w", newline="") as handle:
            writer = csv.DictWriter(
                handle,
                fieldnames=[
                    "script",
                    "amplitude_key",
                    "old_value",
                    "new_value",
                    "predicted_new_from_old",
                    "ratio",
                ],
            )
            writer.writeheader()
            writer.writerows(comparison_rows)

        if comparison_rows:
            ratios = np_array = [row["ratio"] for row in comparison_rows if isinstance(row["ratio"], float) and math.isfinite(row["ratio"])]
            summary["comparison"] = {
                "n_rows": len(comparison_rows),
                "csv": str(csv_path),
                "ratio_mean": float(sum(ratios) / len(ratios)) if ratios else math.nan,
                "ratio_min": float(min(ratios)) if ratios else math.nan,
                "ratio_max": float(max(ratios)) if ratios else math.nan,
            }
        else:
            summary["comparison"] = {"n_rows": 0, "csv": str(csv_path)}

        summary["log_file"] = str(log_path)
        save_json(results_root / "summary.json", summary)
        save_json(results_root / "final_summary.json", summary)
        print(json.dumps(to_native(summary), sort_keys=True))
        return 0
    except Exception as exc:
        logging.exception("apply_tosc_and_refit.py failed")
        return error_exit(results_root, str(exc))


if __name__ == "__main__":
    raise SystemExit(main())
