#!/usr/bin/env python3
# Auto-generated by apply_tosc_and_refit.py from measure_gamma_and_refit.py
# Uses T_OSC = 1.5 and replaces tp**(3/2) or x**(3/2) factors with (./T_OSC)**(3/2)
# Lattice-only mode: optional ODE loading disabled in the generated copy
from __future__ import annotations

import argparse
import json
import math
import os
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from joblib import Parallel, delayed
from scipy.interpolate import interp1d
from scipy.optimize import least_squares

ROOT = Path(__file__).resolve().parent
T_OSC = 1.5
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from ode.hom_ODE.percolation import PercolationCache


RHO_CANDIDATES = [
    ROOT / "rho_noPT_data.txt",
    ROOT / "lattice_data/data/rho_noPT_data.txt",
    ROOT / "lattice_data/rho_noPT_data.txt",
]
LATTICE_RAW_CANDIDATES = [
    ROOT / "energy_ratio_by_theta_data_v9.txt",
    ROOT / "lattice_data/data/energy_ratio_by_theta_data_v9.txt",
]
LATTICE_SCAN_CANDIDATES = {
    0.5: [ROOT / "xi_lattice_scan_H0p5.txt"],
    1.0: [ROOT / "xi_lattice_scan_H1p0.txt"],
    1.5: [ROOT / "xi_lattice_scan_H1p5.txt", ROOT / "results_hstar/xi_lattice_scan_H1p5.txt"],
    2.0: [ROOT / "xi_lattice_scan_H2p0.txt", ROOT / "results_hstar/xi_lattice_scan_H2p0.txt"],
}
ODE_CANDIDATES = []
BEST_BETA_CANDIDATES = [
    ROOT / "results_collapse/best_beta.json",
    ROOT / "results_collapse_v9_H15H20/best_beta.json",
]
GLOBAL_FIT_CANDIDATES = [
    ROOT / "results_collapse/global_fit.json",
    ROOT / "results_collapse_v9_H15H20/global_fit.json",
]
FINF_TAIL_CANDIDATES = [
    ROOT / "results_collapse/Finf_tail.csv",
    ROOT / "results_collapse_v9_H15H20/Finf_tail.csv",
]
DEFAULT_TARGET_H = [0.5, 1.0, 1.5, 2.0]


def parse_args():
    p = argparse.ArgumentParser(description="Measure gamma(H-amplitude exponent) and refit the two-exponent xi model.")
    p.add_argument("--rho", type=str, default="")
    p.add_argument("--lattice-raw", type=str, default="")
    p.add_argument("--ode", type=str, default="")
    p.add_argument("--best-beta", type=str, default="")
    p.add_argument("--collapse-fit", type=str, default="")
    p.add_argument("--finf-tail", type=str, default="")
    p.add_argument("--fixed-vw", type=float, default=0.9)
    p.add_argument("--h-values", type=float, nargs="+", default=DEFAULT_TARGET_H)
    p.add_argument("--grid-n", type=int, default=70)
    p.add_argument("--bootstrap", type=int, default=200)
    p.add_argument("--bootstrap-jobs", type=int, default=max(os.cpu_count() or 1, 1))
    p.add_argument("--bootstrap-seed", type=int, default=12345)
    p.add_argument("--free-beta", action="store_true", help="Refine beta within +/-10% of the collapse value.")
    p.add_argument("--skip-ode", action="store_true", help="Do not include optional ODE data even if it is available.")
    p.add_argument("--scalar-only", action="store_true", help="Fit only the scalar-gamma model and skip the gamma(theta)=gamma0+gamma1 cos(theta) nonlinear refit.")
    p.add_argument("--outdir", type=str, default="results_gamma")
    p.add_argument("--dpi", type=int, default=220)
    return p.parse_args()


def to_native(obj):
    if isinstance(obj, dict):
        return {str(k): to_native(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [to_native(v) for v in obj]
    if isinstance(obj, np.ndarray):
        return [to_native(v) for v in obj.tolist()]
    if isinstance(obj, (np.floating,)):
        return float(obj)
    if isinstance(obj, (np.integer,)):
        return int(obj)
    return obj


def save_json(path: Path, payload):
    path.write_text(json.dumps(to_native(payload), indent=2, sort_keys=True))


def error_exit(outdir: Path, message: str, code: int = 1):
    outdir.mkdir(parents=True, exist_ok=True)
    payload = {"status": "error", "message": message}
    save_json(outdir / "_error.json", payload)
    print(json.dumps(payload, indent=2, sort_keys=True))
    return code


def resolve_first_existing(candidates, user_value=""):
    if user_value:
        p = Path(user_value).resolve()
        if p.exists():
            return p
        raise FileNotFoundError(f"Missing requested file: {p}")
    for candidate in candidates:
        if candidate.exists():
            return candidate.resolve()
    return None


def potential(theta):
    theta = np.asarray(theta, dtype=np.float64)
    return 1.0 - np.cos(theta)


def rel_rmse(y, yfit):
    y = np.asarray(y, dtype=np.float64)
    yfit = np.asarray(yfit, dtype=np.float64)
    return float(np.sqrt(np.mean(np.square((yfit - y) / np.maximum(y, 1.0e-12)))))


def nearest_theta(theta_values, theta0, atol=5.0e-4):
    theta_values = np.asarray(theta_values, dtype=np.float64)
    idx = int(np.argmin(np.abs(theta_values - float(theta0))))
    if abs(theta_values[idx] - float(theta0)) > atol:
        raise RuntimeError(f"No theta match for theta={theta0:.10f}")
    return idx


def dataset_tag(hstar):
    return f"H{str(float(hstar)).replace('.', 'p')}"


def theta_key_lookup(mapping: dict, theta: float, atol: float = 5.0e-4):
    pairs = []
    for key in mapping:
        try:
            pairs.append((float(key), key))
        except ValueError:
            continue
    if not pairs:
        raise KeyError(f"No numeric theta keys found for theta={theta}")
    vals = np.asarray([p[0] for p in pairs], dtype=np.float64)
    idx = int(np.argmin(np.abs(vals - float(theta))))
    if abs(vals[idx] - float(theta)) > atol:
        raise KeyError(f"No theta key match within tolerance for theta={theta}")
    return mapping[pairs[idx][1]]


def load_f0_table(path: Path, target_h):
    df = pd.read_csv(path, sep=r"\s+", comment="#")
    cols = {c.lower(): c for c in df.columns}
    if {"theta", "f0"} <= set(cols):
        out = df.rename(columns={cols["theta"]: "theta", cols["f0"]: "F0"})[["theta", "F0"]].copy()
        return out.sort_values("theta").reset_index(drop=True)

    theta_col = cols.get("theta0", cols.get("theta"))
    h_col = cols.get("h_pt", cols.get("hstar", cols.get("h")))
    rho_col = cols.get("rho")
    if theta_col is None or h_col is None or rho_col is None:
        raise RuntimeError(
            f"rho_noPT_data.txt must contain either [theta, F0] or [theta0/theta, H_PT/Hstar/H, rho]. Found columns: {list(df.columns)}"
        )
    work = pd.DataFrame(
        {
            "theta": df[theta_col].astype(float),
            "H": df[h_col].astype(float),
            "rho": df[rho_col].astype(float),
        }
    )
    work = work[np.isfinite(work["theta"]) & np.isfinite(work["H"]) & np.isfinite(work["rho"])].copy()
    work = work[work["H"].isin(target_h)].copy()
    if work.empty:
        raise RuntimeError("Could not reconstruct F0(theta): no rho_noPT rows for target H values.")
    work["F0_raw"] = work["rho"] / np.maximum(potential(work["theta"].to_numpy()) * np.power(work["H"].to_numpy(), 1.5), 1.0e-18)
    out = work.groupby("theta", as_index=False)["F0_raw"].median().rename(columns={"F0_raw": "F0"})
    return out.sort_values("theta").reset_index(drop=True)


def merge_f0(df: pd.DataFrame, f0_table: pd.DataFrame):
    theta_ref = f0_table["theta"].to_numpy(dtype=np.float64)
    f0_ref = f0_table["F0"].to_numpy(dtype=np.float64)
    out = df.copy()
    indices = [nearest_theta(theta_ref, th) for th in out["theta"].to_numpy(dtype=np.float64)]
    out["theta"] = [float(theta_ref[i]) for i in indices]
    out["F0"] = [float(f0_ref[i]) for i in indices]
    return out


def parse_prepared_scan(path: Path, hstar: float):
    df = pd.read_csv(path, sep=r"\s+|,", engine="python", comment="#")
    if not {"theta", "tp", "xi"}.issubset({str(c).lower() for c in df.columns}):
        raw = pd.read_csv(path, sep=r"\s+|,", engine="python", comment="#", header=None)
        if raw.shape[1] < 3:
            raise RuntimeError(f"Prepared scan {path} must contain at least 3 columns [theta, tp, xi].")
        raw = raw.iloc[:, :3].copy()
        raw.columns = ["theta", "tp", "xi"]
        raw["H"] = float(hstar)
        raw["source"] = "lattice"
        return raw[["theta", "tp", "xi", "H", "source"]].astype({"theta": float, "tp": float, "xi": float, "H": float})

    cols = {c.lower(): c for c in df.columns}
    out = pd.DataFrame(
        {
            "theta": df[cols["theta"]].astype(float),
            "tp": df[cols["tp"]].astype(float),
            "xi": df[cols["xi"]].astype(float),
            "H": float(hstar) if "h" not in cols and "hstar" not in cols else df[cols.get("h", cols.get("hstar"))].astype(float),
            "source": "lattice",
        }
    )
    return out[np.isfinite(out["theta"]) & np.isfinite(out["tp"]) & np.isfinite(out["xi"]) & np.isfinite(out["H"])].copy()


def load_lattice_data(raw_path: Path | None, fixed_vw: float, target_h):
    per_h = []
    explicit_count = 0
    for hstar in target_h:
        explicit = resolve_first_existing(LATTICE_SCAN_CANDIDATES.get(hstar, []), "")
        if explicit is not None:
            explicit_count += 1
            per_h.append(parse_prepared_scan(explicit, hstar))
    if explicit_count == len(target_h):
        return pd.concat(per_h, ignore_index=True)

    if raw_path is None or not raw_path.exists():
        raise FileNotFoundError("Missing lattice xi inputs. Supply raw energy_ratio_by_theta_data_v9.txt or prepared xi_lattice_scan_H*.txt files.")

    df = pd.read_csv(raw_path, sep=r"\s+", comment="#")
    cols = {c.lower(): c for c in df.columns}
    theta_col = cols.get("theta0", cols.get("theta"))
    h_col = cols.get("h_pt", cols.get("hstar", cols.get("h")))
    beta_over_h_col = cols.get("beta_over_h")
    xi_col = cols.get("mean_ratio", cols.get("xi"))
    if theta_col is None or h_col is None or beta_over_h_col is None or xi_col is None:
        raw = pd.read_csv(raw_path, sep=r"\s+", comment="#", header=None)
        if raw.shape[1] < 7:
            raise RuntimeError(f"Raw lattice xi file {raw_path} must contain 7 columns [theta, H, beta_over_H, beta, mean_ratio, std_ratio, N_samples].")
        raw = raw.iloc[:, :7].copy()
        raw.columns = ["theta", "H", "beta_over_H", "beta", "xi", "std_ratio", "N_samples"]
        df = raw
        theta_col = "theta"
        h_col = "H"
        beta_over_h_col = "beta_over_H"
        xi_col = "xi"

    work = pd.DataFrame(
        {
            "theta": df[theta_col].astype(float),
            "H": df[h_col].astype(float),
            "beta_over_H": df[beta_over_h_col].astype(float),
            "xi": df[xi_col].astype(float),
            "source": "lattice",
        }
    )
    work = work[np.isfinite(work["theta"]) & np.isfinite(work["H"]) & np.isfinite(work["beta_over_H"]) & np.isfinite(work["xi"])].copy()
    work = work[work["H"].isin(target_h)].copy()
    perc = PercolationCache()
    work["tp"] = [perc.get(float(h), float(bh), float(fixed_vw)) for h, bh in zip(work["H"], work["beta_over_H"])]
    return work.sort_values(["H", "theta", "tp"]).reset_index(drop=True)


def load_optional_ode(path: Path | None, fixed_vw: float, target_h):
    if path is None or not path.exists():
        return None
    df = pd.read_csv(path, sep=r"\s+|,", engine="python", comment="#")
    cols = {c.lower(): c for c in df.columns}
    if {"theta", "tp", "xi"}.issubset(cols):
        h_col = cols.get("h", cols.get("hstar"))
        out = pd.DataFrame(
            {
                "theta": df[cols["theta"]].astype(float),
                "tp": df[cols["tp"]].astype(float),
                "xi": df[cols["xi"]].astype(float),
                "H": 1.0 if h_col is None else df[h_col].astype(float),
                "source": "ode",
            }
        )
        out = out[np.isfinite(out["theta"]) & np.isfinite(out["tp"]) & np.isfinite(out["xi"]) & np.isfinite(out["H"])].copy()
        return out[out["H"].isin(target_h)].copy()

    raw = pd.read_csv(path, sep=r"\s+|,", engine="python", comment="#", header=None)
    if raw.shape[1] < 6:
        raise RuntimeError(f"Could not parse ODE xi file {path}")
    raw = raw.iloc[:, :6].copy()
    raw.columns = ["vw", "theta", "H", "beta_over_H", "tp", "xi"]
    out = pd.DataFrame(
        {
            "vw": raw["vw"].astype(float),
            "theta": raw["theta"].astype(float),
            "H": raw["H"].astype(float),
            "tp": raw["tp"].astype(float),
            "xi": raw["xi"].astype(float),
            "source": "ode",
        }
    )
    out = out[np.isclose(out["vw"], float(fixed_vw), atol=1.0e-12, rtol=0.0)].copy()
    out = out[np.isfinite(out["theta"]) & np.isfinite(out["tp"]) & np.isfinite(out["xi"]) & np.isfinite(out["H"])].copy()
    return out[out["H"].isin(target_h)].copy()


def compute_x(df: pd.DataFrame, beta: float):
    out = df.copy()
    out["x"] = out["tp"].to_numpy(dtype=np.float64) * np.power(out["H"].to_numpy(dtype=np.float64), float(beta))
    out["fanh"] = out["xi"].to_numpy(dtype=np.float64) * out["F0"].to_numpy(dtype=np.float64) / np.power((out["tp"].to_numpy(dtype=np.float64)) / T_OSC, 1.5)
    return out


def loglog_interp(x, y, xgrid):
    x = np.asarray(x, dtype=np.float64)
    y = np.asarray(y, dtype=np.float64)
    xgrid = np.asarray(xgrid, dtype=np.float64)
    mask = np.isfinite(x) & np.isfinite(y) & (x > 0.0) & (y > 0.0)
    if np.sum(mask) < 2:
        return np.full_like(xgrid, np.nan, dtype=np.float64)
    x = x[mask]
    y = y[mask]
    order = np.argsort(x)
    x = x[order]
    y = y[order]
    x, uniq_idx = np.unique(x, return_index=True)
    y = y[uniq_idx]
    if len(x) < 2:
        return np.full_like(xgrid, np.nan, dtype=np.float64)
    f = interp1d(np.log(x), np.log(y), kind="linear", bounds_error=False, fill_value=np.nan, assume_sorted=True)
    out = np.exp(f(np.log(xgrid)))
    out[(xgrid < x[0]) | (xgrid > x[-1])] = np.nan
    return out


def slope_fit_logH(logH, logf):
    logH = np.asarray(logH, dtype=np.float64)
    logf = np.asarray(logf, dtype=np.float64)
    A = np.vstack([np.ones_like(logH), logH]).T
    coeff, *_ = np.linalg.lstsq(A, logf, rcond=None)
    resid = logf - A @ coeff
    dof = max(len(logH) - 2, 1)
    s2 = float(np.sum(np.square(resid)) / dof)
    try:
        cov = s2 * np.linalg.inv(A.T @ A)
        slope_err = float(np.sqrt(cov[1, 1]))
    except np.linalg.LinAlgError:
        slope_err = np.nan
    return float(coeff[1]), slope_err


def build_gamma_tables(df: pd.DataFrame, grid_n: int, outdir: Path):
    per_x_rows = []
    cell_rows = []
    theta_values = np.array(sorted(df["theta"].unique()), dtype=np.float64)

    for theta in theta_values:
        sub = df[np.isclose(df["theta"], theta, atol=5.0e-4, rtol=0.0)].copy()
        if sub.empty:
            continue
        by_h = {}
        for h, hsub in sub.groupby("H", sort=True):
            by_h[float(h)] = hsub.sort_values("x")[["x", "fanh"]].copy()
        if len(by_h) < 2:
            continue
        xmin = max(float(v["x"].min()) for v in by_h.values())
        xmax = min(float(v["x"].max()) for v in by_h.values())
        if not np.isfinite(xmin) or not np.isfinite(xmax) or xmax <= xmin:
            x_all = np.concatenate([v["x"].to_numpy(dtype=np.float64) for v in by_h.values()])
            xmin = float(np.min(x_all))
            xmax = float(np.max(x_all))
        xgrid = np.geomspace(xmin, xmax, grid_n)

        interp_map = {h: loglog_interp(v["x"].to_numpy(dtype=np.float64), v["fanh"].to_numpy(dtype=np.float64), xgrid) for h, v in by_h.items()}

        for ix, xnode in enumerate(xgrid):
            hvals = []
            fvals = []
            for h, vals in interp_map.items():
                if ix < len(vals) and np.isfinite(vals[ix]) and vals[ix] > 0.0:
                    hvals.append(float(h))
                    fvals.append(float(vals[ix]))
            n_h = len(hvals)
            if n_h < 2:
                continue
            gamma, gamma_err = slope_fit_logH(np.log(hvals), np.log(fvals))
            per_x_rows.append(
                {
                    "theta": float(theta),
                    "x": float(xnode),
                    "gamma": float(gamma),
                    "gamma_err": float(gamma_err),
                    "n_H": int(n_h),
                }
            )
            if n_h >= 2:
                mean_logH = float(np.mean(np.log(hvals)))
                mean_logf = float(np.mean(np.log(fvals)))
                for h, f in zip(hvals, fvals):
                    cell_rows.append(
                        {
                            "theta": float(theta),
                            "x": float(xnode),
                            "logH_centered": float(np.log(h) - mean_logH),
                            "logf_centered": float(np.log(f) - mean_logf),
                        }
                    )

    gamma_per_x = pd.DataFrame(per_x_rows).sort_values(["theta", "x"]).reset_index(drop=True)
    gamma_per_x.to_csv(outdir / "gamma_per_x_theta.csv", index=False)

    gamma_by_theta_rows = []
    for theta, sub in gamma_per_x.groupby("theta", sort=True):
        use = sub[sub["n_H"] >= 3].copy()
        if use.empty:
            use = sub
        vals = use["gamma"].to_numpy(dtype=np.float64)
        gamma_by_theta_rows.append(
            {
                "theta": float(theta),
                "gamma_median": float(np.median(vals)),
                "gamma_p16": float(np.percentile(vals, 16.0)),
                "gamma_p84": float(np.percentile(vals, 84.0)),
            }
        )
    gamma_by_theta = pd.DataFrame(gamma_by_theta_rows).sort_values("theta").reset_index(drop=True)
    gamma_by_theta.to_csv(outdir / "gamma_by_theta.csv", index=False)

    cell_df = pd.DataFrame(cell_rows)
    x = cell_df["logH_centered"].to_numpy(dtype=np.float64)
    y = cell_df["logf_centered"].to_numpy(dtype=np.float64)
    gamma_pooled = float(np.dot(x, y) / np.maximum(np.dot(x, x), 1.0e-18))
    resid = y - gamma_pooled * x
    dof = max(len(x) - 1, 1)
    sigma2 = float(np.sum(np.square(resid)) / dof)
    gamma_se = float(np.sqrt(sigma2 / np.maximum(np.dot(x, x), 1.0e-18)))
    ci95 = [gamma_pooled - 1.96 * gamma_se, gamma_pooled + 1.96 * gamma_se]
    t_stat = float(gamma_pooled / np.maximum(gamma_se, 1.0e-18))
    p_value = float(math.erfc(abs(t_stat) / math.sqrt(2.0)))
    pooled_payload = {
        "gamma": gamma_pooled,
        "gamma_err": gamma_se,
        "gamma_ci95": ci95,
        "p_value_gamma_eq_0": p_value,
        "n_obs": int(len(cell_df)),
        "n_cells": int(cell_df[["theta", "x"]].drop_duplicates().shape[0]),
    }
    save_json(outdir / "gamma_pooled.json", pooled_payload)
    return gamma_per_x, gamma_by_theta, pooled_payload, cell_df


def fit_gamma_theta_cos(gamma_by_theta: pd.DataFrame):
    theta = gamma_by_theta["theta"].to_numpy(dtype=np.float64)
    y = gamma_by_theta["gamma_median"].to_numpy(dtype=np.float64)
    sigma = 0.5 * np.maximum(gamma_by_theta["gamma_p84"].to_numpy(dtype=np.float64) - gamma_by_theta["gamma_p16"].to_numpy(dtype=np.float64), 1.0e-6)
    w = 1.0 / np.square(sigma)

    A0 = np.ones((len(theta), 1), dtype=np.float64)
    A1 = np.column_stack([np.ones(len(theta), dtype=np.float64), np.cos(theta)])
    Aw0 = A0 * np.sqrt(w[:, None])
    Aw1 = A1 * np.sqrt(w[:, None])
    yw = y * np.sqrt(w)
    c0, *_ = np.linalg.lstsq(Aw0, yw, rcond=None)
    c1, *_ = np.linalg.lstsq(Aw1, yw, rcond=None)
    res0 = y - A0 @ c0
    res1 = y - A1 @ c1
    rss0 = float(np.sum(w * np.square(res0)))
    rss1 = float(np.sum(w * np.square(res1)))
    n = len(theta)
    aic0 = float(n * math.log(max(rss0, 1.0e-18) / n) + 2.0 * 1)
    bic0 = float(n * math.log(max(rss0, 1.0e-18) / n) + 1.0 * math.log(n))
    aic1 = float(n * math.log(max(rss1, 1.0e-18) / n) + 2.0 * 2)
    bic1 = float(n * math.log(max(rss1, 1.0e-18) / n) + 2.0 * math.log(n))
    return {
        "constant": {"gamma0": float(c0[0]), "AIC": aic0, "BIC": bic0},
        "cos_model": {"gamma0": float(c1[0]), "gamma1": float(c1[1]), "AIC": aic1, "BIC": bic1},
    }


def gamma_theta_scalar(theta_values, gamma):
    return np.full(len(theta_values), float(gamma), dtype=np.float64)


def gamma_theta_cos(theta_values, gamma0, gamma1):
    return float(gamma0) + float(gamma1) * np.cos(np.asarray(theta_values, dtype=np.float64))


def xi_model(df: pd.DataFrame, theta_values: np.ndarray, params: np.ndarray, beta_fixed: float | None, gamma_mode: str):
    params = np.asarray(params, dtype=np.float64)
    idx = 0
    if beta_fixed is None:
        beta = float(params[idx])
        idx += 1
    else:
        beta = float(beta_fixed)
    if gamma_mode == "scalar":
        gamma_theta_vals = gamma_theta_scalar(theta_values, params[idx])
        idx += 1
    else:
        gamma_theta_vals = gamma_theta_cos(theta_values, params[idx], params[idx + 1])
        idx += 2
    t_c = float(params[idx])
    r = float(params[idx + 1])
    idx += 2
    finf = np.asarray(params[idx:], dtype=np.float64)

    theta_index = np.array([nearest_theta(theta_values, th) for th in df["theta"].to_numpy(dtype=np.float64)], dtype=np.int64)
    tp = df["tp"].to_numpy(dtype=np.float64)
    H = df["H"].to_numpy(dtype=np.float64)
    x = tp * np.power(H, beta)
    f0 = df["F0"].to_numpy(dtype=np.float64)
    f_univ = finf[theta_index] / np.maximum(f0, 1.0e-18) + f0 / (np.power((x) / T_OSC, 1.5) * (1.0 + np.power(x / max(t_c, 1.0e-12), r)))
    f_anhr = np.power(H, gamma_theta_vals[theta_index]) * f_univ
    xi_fit = np.power((tp) / T_OSC, 1.5) * f_anhr / np.maximum(f0, 1.0e-18)
    return {
        "beta": beta,
        "gamma_theta": gamma_theta_vals,
        "t_c": t_c,
        "r": r,
        "F_inf": finf,
        "theta_index": theta_index,
        "x": x,
        "xi_fit": xi_fit,
        "f_univ": f_univ,
        "f_anhr": f_anhr,
    }


def fit_twoexp_model(df: pd.DataFrame, theta_values: np.ndarray, init_beta: float, init_gamma: float, init_tc: float, init_r: float, init_finf: np.ndarray, free_beta: bool, gamma_mode: str):
    if gamma_mode not in {"scalar", "cos"}:
        raise ValueError("gamma_mode must be 'scalar' or 'cos'")

    if free_beta:
        lower_beta = 0.9 * init_beta if init_beta >= 0 else 1.1 * init_beta
        upper_beta = 1.1 * init_beta if init_beta >= 0 else 0.9 * init_beta
        lower_beta, upper_beta = sorted([lower_beta, upper_beta])
    x0 = []
    lower = []
    upper = []
    if free_beta:
        x0.append(init_beta)
        lower.append(lower_beta)
        upper.append(upper_beta)

    x0.append(init_gamma)
    lower.append(-3.0)
    upper.append(3.0)
    if gamma_mode == "cos":
        x0.append(0.0)
        lower.append(-3.0)
        upper.append(3.0)
    x0.extend([init_tc, init_r])
    lower.extend([1.0e-3, 0.1])
    upper.extend([20.0, 20.0])
    x0.extend(init_finf.tolist())
    lower.extend([1.0e-6] * len(theta_values))
    upper.extend([1.0e4] * len(theta_values))
    x0 = np.asarray(x0, dtype=np.float64)
    lower = np.asarray(lower, dtype=np.float64)
    upper = np.asarray(upper, dtype=np.float64)

    def resid(par):
        rec = xi_model(df, theta_values, par, None if free_beta else init_beta, gamma_mode)
        return (rec["xi_fit"] - df["xi"].to_numpy(dtype=np.float64)) / np.maximum(df["xi"].to_numpy(dtype=np.float64), 1.0e-12)

    res0 = least_squares(resid, x0=x0, bounds=(lower, upper), loss="soft_l1", f_scale=0.05, max_nfev=8000)
    res = least_squares(resid, x0=res0.x, bounds=(lower, upper), loss="linear", max_nfev=8000)
    rec = xi_model(df, theta_values, res.x, None if free_beta else init_beta, gamma_mode)
    resid_vec = (rec["xi_fit"] - df["xi"].to_numpy(dtype=np.float64)) / np.maximum(df["xi"].to_numpy(dtype=np.float64), 1.0e-12)
    rss = float(np.sum(np.square(resid_vec)))
    n = len(df)
    k = len(res.x)
    dof = max(n - k, 1)
    try:
        cov = (rss / dof) * np.linalg.inv(res.jac.T @ res.jac)
    except np.linalg.LinAlgError:
        cov = np.full((k, k), np.nan, dtype=np.float64)
    aic = float(n * math.log(max(rss, 1.0e-18) / n) + 2.0 * k)
    bic = float(n * math.log(max(rss, 1.0e-18) / n) + k * math.log(n))
    return {
        "success": bool(res.success),
        "message": res.message,
        "params": res.x,
        "covariance": cov,
        "theta_values": theta_values,
        "rel_rmse": rel_rmse(df["xi"].to_numpy(dtype=np.float64), rec["xi_fit"]),
        "rss_frac": rss,
        "AIC": aic,
        "BIC": bic,
        "dof": dof,
        **rec,
    }


def extract_fit_payload(result: dict, beta_init: float, free_beta: bool, gamma_mode: str):
    params = np.asarray(result["params"], dtype=np.float64)
    cov = np.asarray(result["covariance"], dtype=np.float64)
    idx = 0
    if free_beta:
        beta_val = float(params[idx])
        beta_err = float(np.sqrt(cov[idx, idx])) if np.isfinite(cov[idx, idx]) else np.nan
        idx += 1
    else:
        beta_val = float(beta_init)
        beta_err = 0.0
    if gamma_mode == "scalar":
        gamma_payload = {
            "gamma": float(params[idx]),
            "gamma_err": float(np.sqrt(cov[idx, idx])) if np.isfinite(cov[idx, idx]) else np.nan,
        }
        idx += 1
    else:
        gamma_payload = {
            "gamma0": float(params[idx]),
            "gamma0_err": float(np.sqrt(cov[idx, idx])) if np.isfinite(cov[idx, idx]) else np.nan,
            "gamma1": float(params[idx + 1]),
            "gamma1_err": float(np.sqrt(cov[idx + 1, idx + 1])) if np.isfinite(cov[idx + 1, idx + 1]) else np.nan,
        }
        idx += 2
    t_c = float(params[idx])
    t_c_err = float(np.sqrt(cov[idx, idx])) if np.isfinite(cov[idx, idx]) else np.nan
    r = float(params[idx + 1])
    r_err = float(np.sqrt(cov[idx + 1, idx + 1])) if np.isfinite(cov[idx + 1, idx + 1]) else np.nan
    idx += 2
    finf = {}
    for i, th in enumerate(result["theta_values"]):
        err = float(np.sqrt(cov[idx + i, idx + i])) if np.isfinite(cov[idx + i, idx + i]) else np.nan
        finf[f"{float(th):.10f}"] = {"value": float(params[idx + i]), "err": err}
    return {
        "success": result["success"],
        "message": result["message"],
        "gamma_mode": gamma_mode,
        "beta": beta_val,
        "beta_err": beta_err,
        **gamma_payload,
        "t_c": t_c,
        "t_c_err": t_c_err,
        "r": r,
        "r_err": r_err,
        "F_inf": finf,
        "rel_rmse": result["rel_rmse"],
        "rss_frac": result["rss_frac"],
        "AIC": result["AIC"],
        "BIC": result["BIC"],
        "dof": result["dof"],
        "covariance": result["covariance"].tolist(),
    }


def bootstrap_twoexp(df: pd.DataFrame, best_result: dict, beta_init: float, free_beta: bool, gamma_mode: str, nboot: int, n_jobs: int, seed: int):
    theta_values = best_result["theta_values"]
    xi_fit = best_result["xi_fit"]
    resid = (df["xi"].to_numpy(dtype=np.float64) - xi_fit) / np.maximum(xi_fit, 1.0e-12)
    theta_index = best_result["theta_index"]
    xbest = np.asarray(best_result["params"], dtype=np.float64)
    init_beta = float(best_result["beta"])
    init_gamma = float(xbest[1 if free_beta else 0])
    init_tc = float(best_result["t_c"])
    init_r = float(best_result["r"])
    init_finf = np.asarray(best_result["F_inf"], dtype=np.float64)

    def worker(local_seed):
        rng = np.random.default_rng(local_seed)
        boot = df.copy()
        xi_boot = xi_fit.copy()
        for i in range(len(theta_values)):
            mask = theta_index == i
            sampled = rng.choice(resid[mask], size=np.sum(mask), replace=True)
            xi_boot[mask] = np.maximum(xi_fit[mask] * (1.0 + sampled), 1.0e-10)
        boot["xi"] = xi_boot
        rec = fit_twoexp_model(
            boot,
            theta_values,
            init_beta,
            init_gamma,
            init_tc,
            init_r,
            init_finf,
            free_beta=free_beta,
            gamma_mode=gamma_mode,
        )
        return np.asarray(rec["params"], dtype=np.float64)

    seeds = [seed + i for i in range(nboot)]
    boot_params = Parallel(n_jobs=n_jobs)(delayed(worker)(s) for s in seeds)
    arr = np.asarray(boot_params, dtype=np.float64)
    idx = 0
    payload = {}
    if free_beta:
        payload["beta"] = {q: float(np.percentile(arr[:, idx], p)) for q, p in [("p16", 16.0), ("p50", 50.0), ("p84", 84.0)]}
        idx += 1
    if gamma_mode == "scalar":
        payload["gamma"] = {q: float(np.percentile(arr[:, idx], p)) for q, p in [("p16", 16.0), ("p50", 50.0), ("p84", 84.0)]}
        idx += 1
    else:
        payload["gamma0"] = {q: float(np.percentile(arr[:, idx], p)) for q, p in [("p16", 16.0), ("p50", 50.0), ("p84", 84.0)]}
        payload["gamma1"] = {q: float(np.percentile(arr[:, idx + 1], p)) for q, p in [("p16", 16.0), ("p50", 50.0), ("p84", 84.0)]}
        idx += 2
    payload["t_c"] = {q: float(np.percentile(arr[:, idx], p)) for q, p in [("p16", 16.0), ("p50", 50.0), ("p84", 84.0)]}
    payload["r"] = {q: float(np.percentile(arr[:, idx + 1], p)) for q, p in [("p16", 16.0), ("p50", 50.0), ("p84", 84.0)]}
    idx += 2
    payload["F_inf"] = {}
    for i, th in enumerate(theta_values):
        payload["F_inf"][f"{float(th):.10f}"] = {q: float(np.percentile(arr[:, idx + i], p)) for q, p in [("p16", 16.0), ("p50", 50.0), ("p84", 84.0)]}
    return payload


def plot_gamma_vs_theta(gamma_by_theta: pd.DataFrame, cos_fit: dict, outdir: Path, dpi: int):
    theta = gamma_by_theta["theta"].to_numpy(dtype=np.float64)
    y = gamma_by_theta["gamma_median"].to_numpy(dtype=np.float64)
    yerr = np.vstack(
        [
            y - gamma_by_theta["gamma_p16"].to_numpy(dtype=np.float64),
            gamma_by_theta["gamma_p84"].to_numpy(dtype=np.float64) - y,
        ]
    )
    fig, ax = plt.subplots(figsize=(6.2, 4.4))
    ax.errorbar(theta, y, yerr=yerr, fmt="o", color="tab:blue", label=r"$\gamma_{\rm median}(\theta)$")
    tfit = np.linspace(float(np.min(theta)), float(np.max(theta)), 300)
    ax.plot(tfit, np.full_like(tfit, cos_fit["constant"]["gamma0"]), color="gray", ls="--", label="constant")
    ax.plot(tfit, cos_fit["cos_model"]["gamma0"] + cos_fit["cos_model"]["gamma1"] * np.cos(tfit), color="tab:red", lw=1.8, label=r"$\gamma_0+\gamma_1\cos\theta$")
    ax.set_xlabel(r"$\theta$")
    ax.set_ylabel(r"$\gamma$")
    ax.set_title(r"$\gamma(\theta)$ from fixed-$x$ regressions")
    ax.grid(alpha=0.25)
    ax.legend(frameon=False, fontsize=8)
    fig.tight_layout()
    fig.savefig(outdir / "gamma_vs_theta.png", dpi=dpi)
    plt.close(fig)


def plot_gamma_pooled(cell_df: pd.DataFrame, gamma_pooled: dict, outdir: Path, dpi: int):
    fig, ax = plt.subplots(figsize=(5.8, 4.2))
    ax.plot(cell_df["logH_centered"], cell_df["logf_centered"], "o", ms=2.2, alpha=0.35, color="tab:blue")
    xx = np.linspace(float(cell_df["logH_centered"].min()), float(cell_df["logH_centered"].max()), 200)
    ax.plot(xx, gamma_pooled["gamma"] * xx, color="tab:red", lw=1.8, label=rf"pooled $\gamma={gamma_pooled['gamma']:.3f}$")
    ax.set_xlabel(r"$\log H$ (cell-demeaned)")
    ax.set_ylabel(r"$\log f_{\rm anhr}$ (cell-demeaned)")
    ax.set_title("Pooled fixed-effects gamma fit")
    ax.grid(alpha=0.25)
    ax.legend(frameon=False, fontsize=8)
    fig.tight_layout()
    fig.savefig(outdir / "gamma_pooled_scatter.png", dpi=dpi)
    plt.close(fig)


def representative_thetas(theta_values):
    theta_values = np.array(sorted(theta_values), dtype=np.float64)
    if len(theta_values) <= 6:
        return theta_values
    idx = np.linspace(0, len(theta_values) - 1, 6).round().astype(int)
    return theta_values[np.unique(idx)]


def plot_fanh_by_theta(df: pd.DataFrame, result: dict, outdir: Path, dpi: int):
    reps = representative_thetas(result["theta_values"])
    fig, axes = plt.subplots(2, 3, figsize=(14.0, 8.2))
    for ax, theta in zip(axes.flat, reps):
        sub = df[np.isclose(df["theta"], theta, atol=5.0e-4, rtol=0.0)].copy().sort_values("x")
        idx = nearest_theta(result["theta_values"], theta)
        gamma_theta = result["gamma_theta"][idx]
        xfit = np.geomspace(float(np.min(sub["x"])), float(np.max(sub["x"])), 300)
        f0 = float(sub["F0"].iloc[0])
        finf = float(result["F_inf"][idx])
        f_univ = finf / np.maximum(f0, 1.0e-18) + f0 / (np.power((xfit) / T_OSC, 1.5) * (1.0 + np.power(xfit / max(result["t_c"], 1.0e-12), result["r"])))
        for h, hsub in sub.groupby("H", sort=True):
            ax.plot(hsub["x"], hsub["fanh"], "o", ms=3.0, label=rf"$H={h:g}$")
            ax.plot(xfit, np.power(float(h), gamma_theta) * f_univ, lw=1.5)
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_xlabel(r"$x$")
        ax.set_ylabel("fanh")
        ax.set_title(rf"$\theta={theta:.3f}$")
        ax.grid(alpha=0.25)
    axes.flat[0].legend(frameon=False, fontsize=8)
    fig.tight_layout()
    fig.savefig(outdir / "fanh_vs_x_by_theta.png", dpi=dpi)
    plt.close(fig)


def plot_collapse_overlay(df: pd.DataFrame, result: dict, outdir: Path, dpi: int):
    theta_values = representative_thetas(result["theta_values"])
    fig, axes = plt.subplots(2, 3, figsize=(14.0, 8.2))
    for ax, theta in zip(axes.flat, theta_values):
        sub = df[np.isclose(df["theta"], theta, atol=5.0e-4, rtol=0.0)].copy().sort_values("x")
        xi_fit = result["xi_fit"][sub.index.to_numpy()]
        for h, hsub in sub.groupby("H", sort=True):
            mask = np.isclose(sub["H"], h, atol=1.0e-12, rtol=0.0)
            ax.plot(hsub["x"], hsub["xi"], "o", ms=3.0, label=rf"$H={h:g}$")
            ax.plot(hsub["x"], xi_fit[mask], lw=1.5)
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_xlabel(r"$x$")
        ax.set_ylabel(r"$\xi$")
        ax.set_title(rf"$\theta={theta:.3f}$")
        ax.grid(alpha=0.25)
    axes.flat[0].legend(frameon=False, fontsize=8)
    fig.tight_layout()
    fig.savefig(outdir / "collapse_overlay_with_gamma.png", dpi=dpi)
    plt.close(fig)


def plot_residual_heatmap(df: pd.DataFrame, result: dict, outdir: Path, dpi: int):
    theta_values = np.array(sorted(df["theta"].unique()), dtype=np.float64)
    x = result["x"]
    resid = (df["xi"].to_numpy(dtype=np.float64) - result["xi_fit"]) / np.maximum(result["xi_fit"], 1.0e-12)
    xbins = np.geomspace(float(np.min(x)), float(np.max(x)), 40)
    heat = np.full((len(theta_values), len(xbins) - 1), np.nan, dtype=np.float64)
    for i, theta in enumerate(theta_values):
        mask_theta = np.isclose(df["theta"], theta, atol=5.0e-4, rtol=0.0)
        for j in range(len(xbins) - 1):
            mask_bin = mask_theta & (x >= xbins[j]) & (x < xbins[j + 1])
            if np.any(mask_bin):
                heat[i, j] = float(np.mean(resid[mask_bin]))
    fig, ax = plt.subplots(figsize=(8.8, 4.8))
    pcm = ax.pcolormesh(xbins, np.arange(len(theta_values) + 1), heat, cmap="coolwarm", vmin=-0.2, vmax=0.2, shading="auto")
    ax.set_xscale("log")
    ax.set_xlabel(r"$x$")
    ax.set_ylabel(r"$\theta$ index")
    ax.set_yticks(np.arange(len(theta_values)) + 0.5)
    ax.set_yticklabels([f"{th:.3f}" for th in theta_values])
    ax.set_title("Relative residual heatmap")
    fig.colorbar(pcm, ax=ax, label=r"$(\xi_{\rm data}-\xi_{\rm model})/\xi_{\rm model}$")
    fig.tight_layout()
    fig.savefig(outdir / "residual_heatmap_twoexp.png", dpi=dpi)
    plt.close(fig)


def plot_inversion(df: pd.DataFrame, result: dict, gamma_mode: str, outdir: Path, dpi: int):
    for theta in result["theta_values"]:
        sub = df[np.isclose(df["theta"], theta, atol=5.0e-4, rtol=0.0)].copy().sort_values("x")
        idx = nearest_theta(result["theta_values"], theta)
        gamma_theta = result["gamma_theta"][idx]
        fanh_scaled = sub["fanh"].to_numpy(dtype=np.float64) / np.power(sub["H"].to_numpy(dtype=np.float64), gamma_theta)
        x = sub["x"].to_numpy(dtype=np.float64)
        f0 = sub["F0"].to_numpy(dtype=np.float64)
        xi_adj = np.power((x) / T_OSC, 1.5) * fanh_scaled / np.maximum(f0, 1.0e-18)
        T = np.power((x) / T_OSC, 1.5) * result["F_inf"][idx] / np.maximum(f0 * f0, 1.0e-18)
        D = xi_adj - T
        mask = (D > 0.05) & (D < 0.95) & np.isfinite(D) & (x > 0.0)
        if np.sum(mask) < 3:
            continue
        xfit = x[mask]
        Y = 1.0 / D[mask] - 1.0
        good = np.isfinite(Y) & (Y > 0.0)
        if np.sum(good) < 3:
            continue
        lx = np.log(xfit[good])
        ly = np.log(Y[good])
        slope, _ = slope_fit_logH(lx, ly)
        intercept = float(np.mean(ly) - slope * np.mean(lx))
        fig, ax = plt.subplots(figsize=(5.6, 4.2))
        ax.plot(lx, ly, "o", ms=3.0, label="data")
        xx = np.linspace(float(np.min(lx)), float(np.max(lx)), 200)
        ax.plot(xx, intercept + slope * xx, color="tab:red", lw=1.8, label=rf"fit, slope={slope:.3f}")
        ax.set_xlabel(r"$\log x$")
        ax.set_ylabel(r"$\log Y$")
        ax.set_title(rf"Inversion, $\theta={theta:.3f}$")
        ax.grid(alpha=0.25)
        ax.legend(frameon=False, fontsize=8)
        fig.tight_layout()
        fig.savefig(outdir / f"logY_vs_logx_theta_{theta:.3f}.png", dpi=dpi)
        plt.close(fig)


def plot_beta_gamma_scan(df: pd.DataFrame, result: dict, beta_init: float, gamma_init: float, outdir: Path, dpi: int, gamma_mode: str):
    if gamma_mode != "scalar":
        return
    beta_grid = np.linspace(0.9 * beta_init, 1.1 * beta_init, 25) if abs(beta_init) > 1.0e-10 else np.linspace(-0.1, 0.1, 25)
    gamma_grid = np.linspace(gamma_init - 0.5, gamma_init + 0.5, 25)
    theta_values = result["theta_values"]
    heat = np.full((len(gamma_grid), len(beta_grid)), np.nan, dtype=np.float64)
    base_params = np.asarray(result["params"], dtype=np.float64)
    gamma_idx = 1 if len(base_params) == len(theta_values) + 4 else 0
    tc_idx = gamma_idx + 1
    r_idx = gamma_idx + 2
    free_beta = len(base_params) == len(theta_values) + 4
    for i, gamma in enumerate(gamma_grid):
        for j, beta in enumerate(beta_grid):
            params = base_params.copy()
            if free_beta:
                params[0] = beta
                params[1] = gamma
                rec = xi_model(df, theta_values, params, None, "scalar")
            else:
                params[0] = gamma
                rec = xi_model(df, theta_values, params, beta, "scalar")
            resid = (rec["xi_fit"] - df["xi"].to_numpy(dtype=np.float64)) / np.maximum(df["xi"].to_numpy(dtype=np.float64), 1.0e-12)
            heat[i, j] = float(np.sum(np.square(resid)))
    fig, ax = plt.subplots(figsize=(6.2, 4.8))
    pcm = ax.pcolormesh(beta_grid, gamma_grid, heat, shading="auto", cmap="viridis")
    ax.axvline(beta_init, color="white", ls="--", lw=1.2)
    ax.axhline(gamma_init, color="white", ls="--", lw=1.2)
    ax.set_xlabel(r"$\beta$")
    ax.set_ylabel(r"$\gamma$")
    ax.set_title("Approximate beta-gamma scan")
    fig.colorbar(pcm, ax=ax, label="RSS")
    fig.tight_layout()
    fig.savefig(outdir / "beta_gamma_scan.png", dpi=dpi)
    plt.close(fig)


def evaluate_original_collapse_model(df: pd.DataFrame, theta_values: np.ndarray, beta_init: float, collapse_fit_payload: dict):
    if "F_inf" not in collapse_fit_payload:
        return {"AIC": np.nan, "BIC": np.nan, "rel_rmse": np.nan, "rss_frac": np.nan}
    finf = []
    for th in theta_values:
        try:
            entry = theta_key_lookup(collapse_fit_payload["F_inf"], float(th))
        except KeyError:
            return {"AIC": np.nan, "BIC": np.nan, "rel_rmse": np.nan, "rss_frac": np.nan}
        finf.append(float(entry["value"]))
    params = np.asarray([0.0, float(collapse_fit_payload.get("t_c", 1.5)), float(collapse_fit_payload.get("r", 1.5)), *finf], dtype=np.float64)
    rec = xi_model(df, theta_values, params, beta_init, "scalar")
    resid = (rec["xi_fit"] - df["xi"].to_numpy(dtype=np.float64)) / np.maximum(df["xi"].to_numpy(dtype=np.float64), 1.0e-12)
    rss = float(np.sum(np.square(resid)))
    n = len(df)
    k = len(params)
    aic = float(n * math.log(max(rss, 1.0e-18) / n) + 2.0 * k)
    bic = float(n * math.log(max(rss, 1.0e-18) / n) + k * math.log(n))
    return {"AIC": aic, "BIC": bic, "rel_rmse": rel_rmse(df["xi"].to_numpy(dtype=np.float64), rec["xi_fit"]), "rss_frac": rss}


def main():
    args = parse_args()
    outdir = (ROOT / args.outdir).resolve()
    outdir.mkdir(parents=True, exist_ok=True)

    try:
        rho_path = resolve_first_existing(RHO_CANDIDATES, args.rho)
        best_beta_path = resolve_first_existing(BEST_BETA_CANDIDATES, args.best_beta)
        collapse_fit_path = resolve_first_existing(GLOBAL_FIT_CANDIDATES, args.collapse_fit)
        finf_tail_path = resolve_first_existing(FINF_TAIL_CANDIDATES, args.finf_tail)
        raw_lattice_path = resolve_first_existing(LATTICE_RAW_CANDIDATES, args.lattice_raw)
        ode_path = None if args.skip_ode else resolve_first_existing(ODE_CANDIDATES, args.ode)

        if rho_path is None:
            raise FileNotFoundError("Missing rho_noPT_data.txt")
        if best_beta_path is None:
            raise FileNotFoundError("Missing results_collapse/best_beta.json")

        beta_payload = json.loads(best_beta_path.read_text())
        beta_init = float(beta_payload["beta"])
        collapse_fit_payload = json.loads(collapse_fit_path.read_text()) if collapse_fit_path is not None else {}

        target_h = sorted(set(float(h) for h in args.h_values))
        f0_table = load_f0_table(rho_path, target_h)
        f0_table.to_csv(outdir / "F0_table.csv", index=False)

        lattice_df = load_lattice_data(raw_lattice_path, args.fixed_vw, target_h)
        frames = [lattice_df]
        if ode_path is not None:
            ode_df = load_optional_ode(ode_path, args.fixed_vw, target_h)
            if ode_df is not None and not ode_df.empty:
                frames.append(ode_df)
        df = pd.concat(frames, ignore_index=True)
        df = merge_f0(df, f0_table)
        df = df[np.isfinite(df["F0"]) & (df["F0"] > 0.0)].copy()
        if df.empty:
            raise RuntimeError("No valid xi rows after merging F0.")

        df = compute_x(df, beta_init)
        gamma_per_x, gamma_by_theta, gamma_pooled, cell_df = build_gamma_tables(df, args.grid_n, outdir)
        cos_fit = fit_gamma_theta_cos(gamma_by_theta)
        plot_gamma_vs_theta(gamma_by_theta, cos_fit, outdir, args.dpi)
        plot_gamma_pooled(cell_df, gamma_pooled, outdir, args.dpi)

        theta_values = np.array(sorted(df["theta"].unique()), dtype=np.float64)
        init_tc = float(collapse_fit_payload.get("t_c", 1.5))
        init_r = float(collapse_fit_payload.get("r", 1.5))
        init_gamma = float(gamma_pooled["gamma"]) if np.isfinite(gamma_pooled["gamma"]) else 0.0

        init_finf = np.full(len(theta_values), 1.0e-6, dtype=np.float64)
        if finf_tail_path is not None and finf_tail_path.exists():
            finf_df = pd.read_csv(finf_tail_path)
            for i, th in enumerate(theta_values):
                sub = finf_df[np.isclose(finf_df["theta"], th, atol=5.0e-4, rtol=0.0)]
                if not sub.empty and np.isfinite(sub["F_inf_tail"].iloc[0]):
                    init_finf[i] = max(float(sub["F_inf_tail"].iloc[0]), 1.0e-8)
        if "F_inf" in collapse_fit_payload:
            for i, th in enumerate(theta_values):
                try:
                    entry = theta_key_lookup(collapse_fit_payload["F_inf"], float(th))
                    init_finf[i] = max(float(entry["value"]), 1.0e-8)
                except KeyError:
                    pass

        scalar_result = fit_twoexp_model(df, theta_values, beta_init, init_gamma, init_tc, init_r, init_finf, args.free_beta, "scalar")
        scalar_payload = extract_fit_payload(scalar_result, beta_init, args.free_beta, "scalar")
        save_json(outdir / "global_twoexp_fit.json", scalar_payload)

        cos_payload = None
        if not args.scalar_only:
            cos_result = fit_twoexp_model(df, theta_values, beta_init, init_gamma, init_tc, init_r, init_finf, args.free_beta, "cos")
            cos_payload = extract_fit_payload(cos_result, beta_init, args.free_beta, "cos")

        bootstrap_payload = bootstrap_twoexp(
            df,
            scalar_result,
            scalar_payload["beta"],
            args.free_beta,
            "scalar",
            args.bootstrap,
            args.bootstrap_jobs,
            args.bootstrap_seed,
        )
        save_json(outdir / "bootstrap_twoexp_fit.json", bootstrap_payload)

        plot_fanh_by_theta(df.assign(x=scalar_result["x"]), scalar_result, outdir, args.dpi)
        plot_collapse_overlay(df.assign(x=scalar_result["x"]), scalar_result, outdir, args.dpi)
        plot_residual_heatmap(df.assign(x=scalar_result["x"]), scalar_result, outdir, args.dpi)
        plot_inversion(df.assign(x=scalar_result["x"]), scalar_result, "scalar", outdir, args.dpi)
        plot_beta_gamma_scan(df, scalar_result, beta_init, scalar_payload["gamma"], outdir, args.dpi, "scalar")

        original_eval = evaluate_original_collapse_model(df, theta_values, beta_init, collapse_fit_payload)
        original_aic = float(original_eval["AIC"])
        original_bic = float(original_eval["BIC"])
        original_rmse = float(original_eval["rel_rmse"])
        model_comp = {
            "original_collapsed_model": {"AIC": original_aic, "BIC": original_bic, "rel_rmse": original_rmse},
            "scalar_gamma_model": {"AIC": scalar_payload["AIC"], "BIC": scalar_payload["BIC"], "rel_rmse": scalar_payload["rel_rmse"]},
            "delta_AIC_scalar_minus_original": float(scalar_payload["AIC"] - original_aic) if np.isfinite(original_aic) else np.nan,
            "delta_BIC_scalar_minus_original": float(scalar_payload["BIC"] - original_bic) if np.isfinite(original_bic) else np.nan,
        }
        if cos_payload is not None:
            model_comp["gamma_cos_model"] = {"AIC": cos_payload["AIC"], "BIC": cos_payload["BIC"], "rel_rmse": cos_payload["rel_rmse"]}
            model_comp["delta_AIC_cos_minus_scalar"] = float(cos_payload["AIC"] - scalar_payload["AIC"])
            model_comp["delta_BIC_cos_minus_scalar"] = float(cos_payload["BIC"] - scalar_payload["BIC"])
        save_json(outdir / "model_comparison.json", model_comp)

        final_summary = {
            "status": "ok",
            "beta_used": scalar_payload["beta"],
            "beta_from_collapse": beta_init,
            "gamma_pooled": gamma_pooled["gamma"],
            "gamma_pooled_ci95": gamma_pooled["gamma_ci95"],
            "p_value_gamma_eq_0": gamma_pooled["p_value_gamma_eq_0"],
            "twoexp_fit": {
                "gamma": scalar_payload["gamma"],
                "t_c": scalar_payload["t_c"],
                "r": scalar_payload["r"],
                "rel_rmse": scalar_payload["rel_rmse"],
                "AIC": scalar_payload["AIC"],
                "BIC": scalar_payload["BIC"],
            },
            "model_comparison": model_comp,
            "gamma_theta_cos_fit": None if args.scalar_only else cos_fit,
        }
        save_json(outdir / "final_summary.json", final_summary)
        print(json.dumps(to_native(final_summary), indent=2, sort_keys=True))
        return 0
    except Exception as exc:
        return error_exit(outdir, str(exc))


if __name__ == "__main__":
    raise SystemExit(main())
